release:
  - changed-files:
      - any-glob-to-any-file:
          - pubspec.yaml
          - CHANGELOG.md
          - README.md
          - ios/biometric_storage.podspec
          - macos/biometric_storage.podspec
          - .github/workflows/**
